export enum PERMISSIONS {
  POST_CREATE = 'postCreate',
  POST_VIEW = 'postView',
  POST_EDIT = 'postEdit',
  POST_DELETE = 'postDelete',
  USER_CREATE = 'userCreate',
  USER_VIEW = 'userView',
  USER_EDIT = 'userEdit',
  USER_DELETE = 'userDelete',
  TOPIC_CREATE = 'tagCreate',
  TOPIC_VIEW = 'tagView',
  TOPIC_EDIT = 'tagEdit',
  TOPIC_DELETE = 'tagDelete',
  BANNER_CREATE = 'bannerCreate',
  BANNER_VIEW = 'bannerView',
  BANNER_EDIT = 'bannerEdit',
  BANNER_DELETE = 'bannerDelete',
}
