name: Deploy frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd /data/admin.sib.express
          git pull https://${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }} main
          docker build -f ./docker/node/Dockerfile
